# Site settings
title: Jekyll Scaffolding
email: barbieriignacio@gmail.com
description: "The Jekyll gem makes a jekyll executable available to you in your Terminal window."
baseurl: ""
twitter_username: ignaciobarbieri
github_username:  ibarbieri

# Build settings
markdown: kramdown
permalink: pretty


# The folder destination where Jekyll will write files
#source : layouts/

# The folder destination where Jekyll will write files
destination: www/

# Set the files encoding
encoding: utf-8